### PR TITLE
Fix versioning / external file ref from covenants / broken postinstall out of dev

### LINKED ISSUE #8: Publish a version of interbit-* packages that does not include postinstall step
The postinstall step assumes that webpack is an available dependency and is already run on prepublishOnly.
The webpack dep is a dev dependency and therefore npm i will fail for interbit-* packages after pulling out of dev mode from npm.

### PR DESCRIPTION
**Pull request by nicholeous**
- updated versions to match released versions in some covenants
- updated versions to use packages instead of file reference
- moved externally referenced action creator source into covenant package in which it was referenced
- removed extra postinstall build step that failed on packed covenants/covenants freshly received outside of dev mode from npm (use build/build:watch for local dev when webpack is in context)

Closes #8

### CODE REVIEW

File: packages/utils/src/scripts/distributeTemplate.js [hunk 1]
```diff
@@ -39,11 +38,11 @@ packageFileNames.forEach(packageFileName => {
...
   writeStandardsToPackageJson(packageJsonPath)
   // replace all of the replacable template files
-  templateFileNames.forEach(templateFileName => {
-    const newFileName = templateFileName.replace('template', packageName)
-    console.log(newFileName)
-    fs
-      .createReadStream(templateFileName)
-      .pipe(fs.createWriteStream(newFileName))
-  })
+  // templateFileNames.forEach(templateFileName => {
```
Comment (recurrence) [inline packages/utils/src/scripts/distributeTemplate.js]: ? Stale source?

File: packages/interbit-platform-tools/index.js [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+}
+
+const herokuMap = {
+  accounts: 'account',
+  store: 'app-store',
+  projects: 'app-projects',
+  'interbit.io': 'app-interbit-io'
+}
+
+// const localMap = {
```
Comment (recurrence) [inline packages/interbit-platform-tools/index.js]: Old dns paths?

Comment (nicholeous) [reply packages/interbit-platform-tools/index.js]: This was merged in from Karin's branch and she's taken care of it there. It will disappear on another branch and be merged in there.

File: packages/utils/src/scripts/distributeTemplate.js (hunk 1 above)
Comment (nicholeous) [reply packages/utils/src/scripts/distributeTemplate.js]: See other comment

**Comment by nicholeous** [comment]
The new package has just been published from Karin's branch
